language: python

python:
    - 2.6

install:
    - python boostrap.py -c config/base.cfg
    - bin/buildout -c config/base.cfg -q

notifications:
    irc:
      channels:
        - "irc.freenode.org#milieudefensie"
